services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: mila
      POSTGRES_PASSWORD: 2335
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app -U mila"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: